import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const firaGo = localFont({
  src: "../../public/fonts/Firago/FiraGO_OTF_1001/Roman/FiraGO-ExtraBold.otf",
  weight: "800",
  variable: "--font-firago",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${firaGo.variable} antialiased`}>{children}</body>
    </html>
  );
}
